ADMIN/urls.py
from django.urls import path
from .views import *
app_name = "ADMIN"


urlpatterns = [
    path("login/",login_admin,name="login_admin"),
    path("",Home,name="admin_home"),
    
    
    
    path("profile/<int:pk>/",user_profile,name="user_profile"),
    
    
    #root
    path("root/",admin_root,name="admin_root"),
    path("root/mobile/delete/<int:pk>/",delete_mobile,name="admin_root"),
    #Menu
    path("menu/product_menu/",product_menu,name="product_menu"),
    path("menu/product_menu/create/",product_menu_create,name="product_menu_create"),
    path("menu/product_menu/details/<int:pk>/",product_menu_details,name="product_menu_details"),
    path("menu/product_menu/delete/<int:pk>/",product_menu_delete,name="product_menu_delete"),
    
    path("menu/home/",home_menu,name="home_menu"),
    path("menu/home/create/",home_menu_create,name="home_menu_create"),
    path("menu/home/details/<int:pk>/",home_menu_details,name="home_menu_details"),
    path("menu/home/delete/<int:pk>/",home_menu_delete,name="home_menu_delete"),
    
    
    
    path("menu/help_more/",help_more_menu,name="help_more_menu"),
    path("menu/help_more/create/",help_more_create,name="help_more_create"),
    path("menu/help_more/details/<int:pk>/",help_more_details,name="help_more_details"),
    path("menu/help_more/delete/<int:pk>/",help_more_delete,name="help_more_delete"),
    
    
    
    
    
    path("menu/footer/",footer_menu,name="footer_menu"),
    path("menu/footer/create/",footer_menu_create,name="footer_menu_create"),
    path("menu/footer/details/<int:pk>/",footer_menu_details,name="footer_menu_details"),
    path("menu/footer/delete/<int:pk>/",footer_menu_delete,name="footer_menu_delete"),
    
    
    path("menu/footer_sub/",footer_menuSub,name="footer_menuSub"),
    path("menu/footer_sub/create/",footer_menuSub_create,name="footer_menuSub_create"),
    path("menu/footer_sub/details/<int:pk>/",footer_menuSub_details,name="footer_menuSub_details"),
    path("menu/footer_sub/delete/<int:pk>/",footer_menuSub_delete,name="footer_menuSub_delete"),
    
    
    
    
    path("delivery_man/",delivery_man12,name="delivery_man"),
    path("delivery_man/create/",delivery_man12_create,name="delivery_man_create"),
    path("delivery_man/details/<int:pk>/",delivery_man12_update,name="delivery_man_update"),
    path("delivery_man/delete/<int:pk>/",delivery_man12_delete,name="delivery_man_delete"),
    
    
    path("mail/",mail,name="mail"),
    path("mail/details/<int:pk>/",mail_details,name="mail_details"),
    
    
    path("order/",admin_order_list,name="admin_order_list"),
    path("order/details/<int:pk>/",admin_order_details,name="admin_order_details"),
    path("order/details/<int:pk>/",admin_order_details,name="admin_order_details"),
    path("order/details/<int:pk>/pdf/",admin_order_pdf,name="admin_order_pdf"),
    
    
    
    path("product/",admin_product_list,name="admin_product_list"),
    path("product/details/<int:pk>/",admin_product_list_details,name="admin_product_list_details"),
    path("product/create/",admin_product_create,name="admin_product_create"),
    path("product/delete/<int:pk>/",admin_product_delete,name="admin_product_delete"),
    
    #Business Code
    path("business/client/",business_client,name="business_client"),
    path("business/corporate/",business_corporate,name="business_corporate"),
    path("business/request/",business_request,name="business_request"),
    path("business/request/view/<int:pk>/",business_request_view,name="business_request_view"),
    
    
    path("d_feature/",d_feature,name="d_feature"),
    path("notification/",notification_view,name="notification_view"),
    path("p_request/",p_request,name="product_request"),
    
    
    path("city/",city_view,name="city_view"),
    
    path("area/",area_view,name="area_view"),
    
    
    path("team/",team,name="team"),
    
    
    
    path("offer_code/",offer_code,name="offer_code"),
]

Chaldal/urls.py
from django.contrib import admin
from django.http.response import HttpResponse , JsonResponse
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from index.views import index
from django.views.decorators.csrf import csrf_exempt

from root.views import *


def a(request):
    if request.POST:
        print(request.POST)


    return HttpResponse()
from django.middleware.csrf import get_token

@csrf_exempt
def OMG(request):
    if request.POST:
        print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")


    # request.session['Matols'] = "sdad"
    # print(request.POST)
    print(request.session.session_key)
    print(request.POST)
    print(request.FILES)
    # print(get_token(request))
    alu = {request.POST.get("UserName"):request.POST.get("Password")}
    print(request.POST.get("Image"))
    print(alu)
    return JsonResponse(alu)

urlpatterns = [
    path("turoLove/",OMG),
    path('home/', index,name="index"),
    path('favicon.ico/', a),
    path("admin/",include("ADMIN.urls",namespace="ADMIN")),
    path('admin/chat/', admin_chat),
    path('admina/', admin.site.urls),
    path('signup/',signup,name="signup"),
    path('login/',loginView,name="login"),
    path('logout/',logOutview,name="logout"),
    path("t/",include("support.urls",namespace="support")),
    path('corporate/',include('corporate.urls',namespace='corporate')),
    path("",include("Product.urls",namespace="product")),
    path("customer/",include("customer.urls",namespace="customer")),
    path('verify/<uuid>/',verify_email,name="verify_mail"),
    path('get/next_dlv_time/',next_dlv_time,name="next_dlv_time")

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
# from .views import profile,adress_save,get_api,profile_html,map_or_adressHtml,select_city_Html,post_data2,add_customer_bag,userBagList,checkout,paymentView
from .views import *
from root.views import change_password

app_name="customer"

urlpatterns = [
    path("profile/",profile),
    path("orders/",userOrderDetail,name="userOrdered"),
    path("account-history/",payment_history,name="payment_history"),
    path("select-city/",render_city,name="select_city"),
    path("changepassword/",change_password,name="change_password"),
    
    # order information
    path("checkout/",checkout,name="checkout"),
    path("checkout/payment/",paymentView,name="payment"),
    # api
    path("api/post/",adress_save,name="post_data"),
    path("api/post/add_bag/",add_customer_bag,name="add_bag"),
    path("api/post2/",post_data2,name="post_data2"),
    path("api/post3/",post_data3,name="post_data3"),
    path("api/get/",get_api,name="get_api"),
    path("api/get/html/",profile_html,name="get-profile-html"),
    path("api/get/adress_html/<str:type>/",map_or_adressHtml),
    path("api/get/select-city/",select_city_Html,name="select_city_html"),
    # api get data form bag database
    path("api/get/itemBagList/",userBagList,name="bagList"),

]

customer/forms.py
from django.db.models import fields

from django import forms
from .models import Profile
from Product.models import report_choise , Order
from django.core.validators import RegexValidator

class gender_from(forms.ModelForm):
    class Meta:
        fields = ["gender"]
        model  = Profile

class order_report_form(forms.Form):
    orderId = forms.IntegerField(min_value=1)
    report = forms.ChoiceField(choices=report_choise)

class order_star_submit(forms.Form):
    orderId = forms.IntegerField(min_value=1)
    rating = forms.IntegerField(validators=[RegexValidator(regex=r'^[1-5]$')])

class profile_update_form(forms.Form):
    profile_photo = forms.ImageField()

customer/views.py
from django.forms import utils
from django.http.response import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse
from root.utils import almost_same
from root.models import Menu,basic_setting,City,Area,Delivery_Charge_record
from customer.models import Customer_bags,Email_Verify
from Product.models import Product ,Order ,report_choise,Special_Code
from .models import Profile ,user_adress
from django.http import JsonResponse
from json import dumps, loads

from .forms import gender_from , order_report_form ,order_star_submit
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from django.utils.timezone import now
import datetime
# Create your views here.

from django.core.mail import EmailMultiAlternatives
from django.conf import settings

from time import time

def profile(request):
    # user = Profile.objects.select_related("user").get(user=request.user)
                                        # OR
    user = request.user.get_profile
    root =  basic_setting.objects.get()
    print("###############################################")
    city = root.allow_city.all()


    if request.user.is_authenticated:
        user_proifle = request.user.get_profile
        crnt_city = user_proifle.current_city.Name
    elif request.session.get('crnt_city'):
        crnt_city = City.objects.filter(pk=request.session.get('crnt_city'))[0].Name
    else:
       crnt_city = "Dhaka"


    discout_parsent = 0
    if request.session.get('discount_code'):
        try:
            discout_parsent = Special_Code.objects.get(code=request.session.get('discount_code'),expiry_date__gte=datetime.datetime.now(),is_used=False).discount_parsent
        except Special_Code.DoesNotExist:
            del request.session['discount_code']


    pd_offer_count = Product.objects.filter(discord_price__gt=0)
    context={
        "profile":user,
        "city":city,
        "POST_API":reverse("customer:post_data"),
        "is_geo":user.is_geoLocation(),
        "crnt_city":crnt_city,
        "offers":pd_offer_count.count() if pd_offer_count.exists() else 0,
        "discout_parsent":discout_parsent
    }
    context.update(almost_same(basic_setting.objects.get(),Menu))
    return render(request,"chaldal/customer/profile.html",context)

from customer.forms import profile_update_form
from re import findall
from django.template import Template , Context
def post_data2(request):
    post = request.POST
    if post:
        get = request.GET
        if get.get("update_profile"):
            forms = profile_update_form(post,request.FILES)
            if forms.is_valid():
                if request.user.is_authenticated:
                    request.user.get_profile.profile_photo = forms.cleaned_data['profile_photo']
                    request.user.get_profile.save()

                    return JsonResponse({"state":"successful",'data':"Your profile successful updated"})
                return JsonResponse({"state":"err",'data':"Your are not authenticated🙂.Please login first!"})
            return JsonResponse({"state":"err",'data':"File error. Update the right extension formet file🙂"})


        elif get.get("update_current_city"):
            try:
                city = City.objects.get(pk=post["current_city"])
                if request.user.is_authenticated:
                    request.user.get_profile.current_city = city
                    request.user.get_profile.save()


                request.session['crnt_city'] = city.pk
                return JsonResponse({"state":"successful","city":city.Name})
            except City.DoesNotExist:
                return JsonResponse({"err":"403 forbiden"},status=403)

        elif get.get('cancelOrder'):
            user_profile = request.user.get_profile

            try:
                order_id = loads(post['data'])['orderId']
                order_obj = user_profile.get_user_order.filter(pk=order_id)
                if order_obj.exists():
                    order_obj.update(
                        order_status="CN"
                    )
                    routing_url = reverse("customer:payment")+f"?matRout=True&orderId={order_obj.first().pk}"
                    return JsonResponse({"status":"successful","matRout":routing_url,"isLocalSessionclear":True})
            except ValueError:
                pass
            return HttpResponseBadRequest("Bad request No order Found!!!")

        elif get.get('email_varify'):
            print(post.get('email'))
            test_str = findall(r'^[\w.\.]+@\w+\.\D+',post.get('email'))
            if test_str:
                print(test_str[0])

                email_obj = EmailMultiAlternatives(
                    'Varify Your email',
                    f"""Hello dear {request.user},
                    Thanks For visiting our side 💕
                    To Varify your email on <a href="www.google.com"><a>
                    """,
                    settings.EMAIL_HOST_USER,
                    [test_str[0]]
                )
                with open('./templates/chaldal/email.html','r') as f:
                    templates = Template(f.read())
                    vf_obj = Email_Verify.objects.create(profile=request.user.get_profile,email=test_str[0])
                    context = Context({
                        'username':request.user,
                        'varify_link':settings.HOST_NAME +reverse('verify_mail',kwargs={'uuid':vf_obj.key}) if settings.HOST_NAME else f"http://127.0.0.1:8000" +reverse('verify_mail',kwargs={'uuid':vf_obj.key}),
                        'chaldal_img':basic_setting.objects.get().get_logo(),
                        'host':settings.HOST_NAME  if settings.HOST_NAME else "https://chaldal.com/"
                    })
                    full_form_html = templates.render(context)
                email_obj.attach_alternative(full_form_html,'text/html')

                email_obj.send()
            return JsonResponse({"status":"successful"})





from django.db.models import F
def add_customer_bag(request):
    cnt = time()
    POST = request.POST
    if POST:
        if request.user.is_authenticated:
            user_profile = request.user.get_profile
            if POST['type'] == "update":
                try:
                    bag_product = Product.objects.get(pk=POST['prod_id'],city=user_profile.current_city)
                    product_exist = Customer_bags.objects.filter(
                        product=bag_product,
                        profile=user_profile,
                    )
                    if product_exist.exists():
                        print("??????????")
                        product_exist.update(quantity =  POST['quantity'] if int(POST['quantity']) else 1)
                        print(time() - cnt)
                        return JsonResponse({"state":"successful","data":"You have updated the items quantity"})
                    Customer_bags.objects.create(
                        product=bag_product,
                        profile=user_profile,
                        quantity=1
                    )
                    print(time() - cnt)
                    return JsonResponse({"state":"successful",})
                except ValueError:
                    return JsonResponse({"error":"400 Bad request","data":"Don't make bad requests immediately"},status=400)
                except Product.DoesNotExist:
                    return JsonResponse({"state":"faild","data":"This product no longer available"})

            elif POST['type'] == "delete":
                user_profile.get_customerBag_item.filter(product__pk=POST['prod_id']).delete()
                return JsonResponse({"state":"successful",})
            else:
                return JsonResponse({"error":"400 Bad request","data":"Don't make bad requests immediately"},status=400)
        else:return JsonResponse({"error":"Your are not authenticated","data":"Don't make bad requests immediately"},status=400)


def adress_save(request):
    user = request.user.get_profile
    if request.POST:
        get = request.GET
        post = request.POST
        if get.get("map_update"):
           lat= loads(request.POST["map"])["lat"]
           lng = loads(request.POST["map"])["lng"]
           user = request.user.get_profile
           user.location.update_or_create(
                    user = user,
                    defaults={"latitude":lat,"longitude":lng}
                )



           return JsonResponse({"update":"successful"})
        if get.get("get_area"):
            try:
                area = City.objects.get(pk=request.POST.get("city_get")).get_area.all()
                last_added = user.adress.last().area.pk
                html = ''
                for alaka in area:
                    option = "selected" if alaka.pk == last_added else ""
                    html += f"<option {option} value='{alaka.pk}'>{alaka.name}</option>"
                return JsonResponse({"state":"successful","html":html})
            except City.DoesNotExist:
                return JsonResponse({"update":"faild","err":"no area found"})


        if get.get("add_adress"):
            data = loads(post.get("data"))
            city = user.current_city
            area = Area.objects.get(pk=data.get("area"))
            new_adress = user_adress.objects.create(
                user = user ,
                adress = data.get("adress"),
                city = city,
                area = area,
                delivery_parson_name = data.get("name"),
                Phone = data.get("phone"),
            )
            return JsonResponse({"state":"successful","pk":new_adress.pk})

        if get.get("update_adress"):
            print(request.POST)
            data = loads(post.get("data"))
            pk  = data["pk"]
            name  = data["name"]
            adress  = data["adress"]
            phone  = data["phone"]
            city  = user.current_city

templates/chaldal/customer/payment.html
<style>
 #map {
        height: 200px;
}
</style>


<section class="bodyTable">
  <div>
    <div class="checkoutExperience2">
      <div>
        <div class="checkoutConfirmComponent">
          <div class="orderSuccess">
            <img
              src="{{MEDIA_URL}}/grocery-crate2.webp"
            />
            <div class="orderSuccessMessage">
              <div class="orderNum">
                <span>Order Number </span><b><span>#{{orderId}}</span></b>
              </div>
              <div class="thankYou">
                <div><span>Your order is on its way</span></div>
                <div>
                  <span>please pay with <b>cash on delivery</b></span>
                </div>
              </div>
            </div>
          </div>
          <div class="paymentMethods">
            <div class="inlinePaymentComponent">
              <div>
                <h4>
                  <span>Do you want to <b>Pay Now</b>?</span>
                </h4>
                <section class="paymentMethods">
                  <div class="paymentMethodItem" data-payment="1">
                    <div class="Portwallet paymentMethodItemContent">
                      <img
                        src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                        style="
                          background-image: url({{MEDIA_URL}}/payment_icons_portwallet.webp);
                        "
                      />
                      <p>Bangladeshi Credit / Debit Card</p>
                    </div>
                  </div>
                  <div class="paymentMethodItem" data-payment="2">
                    <div class="Bkash paymentMethodItemContent">
                      <img
                        src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                        style="
                          background-image: url({{MEDIA_URL}}/bekash.png);
                        "
                      />
                      <p>bKash</p>
                    </div>
                  </div>
                  <div class="brainTree" data-payment="3">
                    <div class="braintreePaymentContainer">
                      <span>or</span
                      ><button class="braintreePayment">
                        <img
                          src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                          style="
                            background-image: url({{MEDIA_URL}}/paypal.webp);
                          "
                        /><span class="divider">/</span
                        ><span>International Credit Card</span>
                      </button>
                    </div>
                  </div>
                  <div class="" data-payment="4">
                    <div class="oldBkashPaymentContainer">
                      <button class="oldBkashPayment">
                        <img
                          src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                          style="
                            background-image:  url({{MEDIA_URL}}/bekash.png);
                            background-repeat: no-repeat;
                            background-position: center;
                          "
                        /><span>bKash (TrxID method)</span>
                      </button>
                    </div>
                  </div>
                  <form id="braintreeCheckout">
                    <div id="payment-container"></div>
                  </form>
                </section>
                <br />
              </div>
            </div>
          </div>
          <div class="restOfThePage">
            <div class="orderDetails">
              <div class="orderSummary">
                <div class="orderSummaryContent">
                  <h6>Order Summary</h6>
                  <table>
                    <tbody>
                      <tr>
                        <td class="label">Subtotal</td>
                        <td class="value"><span>৳</span><span>{{total_price}}</span></td>
                      </tr>
                      <tr>
                        <td class="label">Delivery Charge</td>
                        <td class="value"><span>৳</span><span>{{delivery_charge}}</span></td>
                      </tr>
                    {% if reusablePrice %}
                      <tr>
                        <td class="label">Reusable Bag</td>
                        <td class="value"><span>৳</span><span>{{reusablePrice}}</span></td>
                      </tr>
                    {% endif %}
                    {% if discount_offer %}
                      <tr>
                        <td class="label">Discount</td>
                        <td class="value" style="color:red;"><span>- ৳</span><span>{{discount_offer}}</span></td>
                      </tr>
                    {% endif %}
                      <tr>
                        <td class="label">Order Total</td>
                        <td class="value"><span>৳</span><span>{{order_total}}</span></td>
                      </tr>
                     


                      <tr>
                        <td class="label walletRed">Amount Paid</td>
                        <td class="value"><span>৳</span><span>0</span></td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <td class="label">Due</td>
                        <td class="value"><span>৳</span><span>{{order_total}}</span></td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
              <div class="orderSummary">
                <div class="deliveryDetails">
                {% if  not geo.status %}
                
                  <h6>Delivery Address</h6>
                  <p>{{Delivery_Address}}</p>
                {% endif %}
              
                  <h6>Preferred Delivery Timings</h6>
                  <div
                    class="deliveryTimeSelectionContainer singleSlotShipment"
                  >
                    <div class="expressDelivery">
                      <div class="deliveryTypeTitle">Express Delivery</div>
                      <div class="deliveryDate">{{Delivery_day}} {{Delivery_mounth}}</div>
                      <div class="deliveryTimeRange">
                        <span>{{Delivery_to_time}}</span><span> - </span><span>{{Delivery_from_time}}</span>
                      </div>
                    </div>
                  </div>
                </div>







                {% if   geo.status %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBWOqMTUtC3VgJPQE39tnbIeLM-yAU4Ijw&callback=initMap&libraries=&v=weekly" async ></script>

              <div id="googleMap" class="deliveryDetails">
                  <p style="text-align:center;font-size:17px;font-weight: 600;margin-bottom: 10px;">
                      Google Map
                  </p>
                 
                  <div id="map"></div>
              </div>

              


              <script>
                var neighborhoods = { lat: {{geo.lat}}, lng: {{geo.lng}} };
                
                var markers = [];
                var map;
                
                function initMap() {
                    map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 16,
                    center:neighborhoods,
                    });
                }

                   // Customizing google map api
              
                    window.setTimeout(() => {
                    markers.push(
                        new google.maps.Marker({
                        position: neighborhoods,
                        map,
                        animation: google.maps.Animation.DROP,
                        })
                    );
                    }, 250);
              
                
                </script>

              {% endif %}










              </div>
            </div>
            <div class="orderInstructionList">
              <label>Order Instructions</label>
              <table>
                <tbody></tbody>
              </table>
            </div>

            <div class="orderInstructionContainer">
              {% if Instructions %}{{Instructions}}{%else%}
              <div>
                <div class="OrderInstructionForm">
                  <textarea
                    placeholder="E.g. Call me when you arrive"
                  ></textarea
                  ><button><span>Submit</span></button>{%endif%}
                </div>


                <script>
                  $('.orderInstructionContainer button').click(()=>{
                      if($('.orderInstructionContainer textarea').val()){
                        $.ajax({
                        type:"POST",
                        url:"{% url 'customer:post_data3' %}?update_order_instructions=True",
                        data:{
                          'csrfmiddlewaretoken': csrfmiddlewaretoken,
                          'instructions':$('.orderInstructionContainer textarea').val(),
                          "orderId":"{{orderId}}"
                        },
                        success:(data)=>{
                          var structions = `
                              <div class="cancelContainer oldinstak">

                                <div class="ModalDialogContainer orderCancelPrompt">
                                  <div style="" class="ModalDialog">
                                    <div class="ModalDialogContent">
                                      <div>
                                        <div class="modal-text">
                                          <h1>Thanks for Order Instructions</h1>
                                          <p style='margin: 20px;'>We received your Instructions. As possiable as we maintain the Instructions. Thanks for guiding us🥰</p>
                                        </div>
                                        <div class="modal-footer">
                                          <button class="btnPrimary">Close</button>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              `
                              $('body').append(structions)
                              $('.OrderInstructionForm').html($('.orderInstructionContainer textarea').val())
                              $('.oldinstak .btnPrimary').click(()=>{
                                $('.oldinstak').remove()

                              })
                        }
                      })
                      }
                  })
                </script>
              </div>
            </div>
            <div class="cancelContainer">
              <div class="cancelContent">
                <label>Would you like to cancel this order?</label
                ><button class="cancelOrderBtn">Cancel Order</button>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
var orderCancel_modals_Html = `
<div class="cancelContainer ordCM">

  <div class="ModalDialogContainer orderCancelPrompt">
    <div style="" class="ModalDialog">
      <div class="ModalDialogContent">
        <div>
          <div class="modal-text">
            <h1>Are you sure?</h1>
            <p>You want to cancel this order?</p>
          </div>
          <div class="modal-footer">
            <button class="btnSecondary">Yes</button>
            <button class="btnPrimary">No</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
`
$(".cancelOrderBtn").click(()=>{
  $(".bodyTable").append(orderCancel_modals_Html)
  $(".modal-footer .btnPrimary").click(()=>{
    $(".ordCM").remove()
  })
  $(".modal-footer .btnSecondary").click(()=>{
    site_ajsxWithPOST({"orderId":$(".orderNum b span").text().split("#")[1]},"{% url 'customer:post_data2' %}?cancelOrder=True")
    $(".ordCM").remove()
  })
})

setTitle('Payment')
</script>

<style>
.orderCancelPrompt .ModalDialog:before{
  background-image:url(https://chaldn.com/asset/Egg.Grocery.Fabric/Egg.Grocery.Web1/1.5.0+Release-2217/Default/components/shared/CancelOrderDialog/images/egg_sad.png?alpha=1&webp=1)
}
</style>