ADMIN/urls.py
from django.urls import path
from .views import *
app_name = "ADMIN"


urlpatterns = [
    path("login/",login_admin,name="login_admin"),
    path("",Home,name="admin_home"),
    
    
    
    path("profile/<int:pk>/",user_profile,name="user_profile"),
    
    
    #root
    path("root/",admin_root,name="admin_root"),
    path("root/mobile/delete/<int:pk>/",delete_mobile,name="admin_root"),
    #Menu
    path("menu/product_menu/",product_menu,name="product_menu"),
    path("menu/product_menu/create/",product_menu_create,name="product_menu_create"),
    path("menu/product_menu/details/<int:pk>/",product_menu_details,name="product_menu_details"),
    path("menu/product_menu/delete/<int:pk>/",product_menu_delete,name="product_menu_delete"),
    
    path("menu/home/",home_menu,name="home_menu"),
    path("menu/home/create/",home_menu_create,name="home_menu_create"),
    path("menu/home/details/<int:pk>/",home_menu_details,name="home_menu_details"),
    path("menu/home/delete/<int:pk>/",home_menu_delete,name="home_menu_delete"),
    
    
    
    path("menu/help_more/",help_more_menu,name="help_more_menu"),
    path("menu/help_more/create/",help_more_create,name="help_more_create"),
    path("menu/help_more/details/<int:pk>/",help_more_details,name="help_more_details"),
    path("menu/help_more/delete/<int:pk>/",help_more_delete,name="help_more_delete"),
    
    
    
    
    
    path("menu/footer/",footer_menu,name="footer_menu"),
    path("menu/footer/create/",footer_menu_create,name="footer_menu_create"),
    path("menu/footer/details/<int:pk>/",footer_menu_details,name="footer_menu_details"),
    path("menu/footer/delete/<int:pk>/",footer_menu_delete,name="footer_menu_delete"),
    
    
    path("menu/footer_sub/",footer_menuSub,name="footer_menuSub"),
    path("menu/footer_sub/create/",footer_menuSub_create,name="footer_menuSub_create"),
    path("menu/footer_sub/details/<int:pk>/",footer_menuSub_details,name="footer_menuSub_details"),
    path("menu/footer_sub/delete/<int:pk>/",footer_menuSub_delete,name="footer_menuSub_delete"),
    
    
    
    
    path("delivery_man/",delivery_man12,name="delivery_man"),
    path("delivery_man/create/",delivery_man12_create,name="delivery_man_create"),
    path("delivery_man/details/<int:pk>/",delivery_man12_update,name="delivery_man_update"),
    path("delivery_man/delete/<int:pk>/",delivery_man12_delete,name="delivery_man_delete"),
    
    
    path("mail/",mail,name="mail"),
    path("mail/details/<int:pk>/",mail_details,name="mail_details"),
    
    
    path("order/",admin_order_list,name="admin_order_list"),
    path("order/details/<int:pk>/",admin_order_details,name="admin_order_details"),
    path("order/details/<int:pk>/",admin_order_details,name="admin_order_details"),
    path("order/details/<int:pk>/pdf/",admin_order_pdf,name="admin_order_pdf"),
    
    
    
    path("product/",admin_product_list,name="admin_product_list"),
    path("product/details/<int:pk>/",admin_product_list_details,name="admin_product_list_details"),
    path("product/create/",admin_product_create,name="admin_product_create"),
    path("product/delete/<int:pk>/",admin_product_delete,name="admin_product_delete"),
    
    #Business Code
    path("business/client/",business_client,name="business_client"),
    path("business/corporate/",business_corporate,name="business_corporate"),
    path("business/request/",business_request,name="business_request"),
    path("business/request/view/<int:pk>/",business_request_view,name="business_request_view"),
    
    
    path("d_feature/",d_feature,name="d_feature"),
    path("notification/",notification_view,name="notification_view"),
    path("p_request/",p_request,name="product_request"),
    
    
    path("city/",city_view,name="city_view"),
    
    path("area/",area_view,name="area_view"),
    
    
    path("team/",team,name="team"),
    
    
    
    path("offer_code/",offer_code,name="offer_code"),
]

Chaldal/urls.py
from django.contrib import admin
from django.http.response import HttpResponse , JsonResponse
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from index.views import index
from django.views.decorators.csrf import csrf_exempt

from root.views import *


def a(request):
    if request.POST:
        print(request.POST)


    return HttpResponse()
from django.middleware.csrf import get_token

@csrf_exempt
def OMG(request):
    if request.POST:
        print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")


    # request.session['Matols'] = "sdad"
    # print(request.POST)
    print(request.session.session_key)
    print(request.POST)
    print(request.FILES)
    # print(get_token(request))
    alu = {request.POST.get("UserName"):request.POST.get("Password")}
    print(request.POST.get("Image"))
    print(alu)
    return JsonResponse(alu)

urlpatterns = [
    path("turoLove/",OMG),
    path('home/', index,name="index"),
    path('favicon.ico/', a),
    path("admin/",include("ADMIN.urls",namespace="ADMIN")),
    path('admin/chat/', admin_chat),
    path('admina/', admin.site.urls),
    path('signup/',signup,name="signup"),
    path('login/',loginView,name="login"),
    path('logout/',logOutview,name="logout"),
    path("t/",include("support.urls",namespace="support")),
    path('corporate/',include('corporate.urls',namespace='corporate')),
    path("",include("Product.urls",namespace="product")),
    path("customer/",include("customer.urls",namespace="customer")),
    path('verify/<uuid>/',verify_email,name="verify_mail"),
    path('get/next_dlv_time/',next_dlv_time,name="next_dlv_time")

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

support/urls.py
from django.urls import path ,re_path
from support.views import *

app_name = 'support'

urlpatterns = [
    path('api/',api,name='api'),
    path('post/',helpPost,name='contuctUs'),
    path('<slug>/',mainView,name='mainView'),

    # path('AboutUs/')
]

support/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse
from customer.models import Profile

# Create your models here.
class support_menu(models.Model):
    name = models.CharField(max_length=30)
    img = models.ImageField(upload_to='support/menu',null=True,blank=True)
    slug = models.SlugField(editable=False)
    body = RichTextField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def url(self):
        menu_slug = slugify(self.name)
        s_url = reverse('support:api')
        return f'{s_url}?menu={menu_slug}'

    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(support_menu,self).save(*args, **kwargs)



class Team(models.Model):
    name = models.CharField(max_length=60)
    occupation = models.CharField(max_length=120,null=True,blank=True)
    photo = models.ImageField(upload_to='support/Team',null=True,blank=True)
    discription = RichTextField()

    def __str__(self):
         return self.name
ContactUs_choice =  (
        ("Y","Read"),
        ("N","New Mail"),
)

class ContactUs(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
    name = models.CharField(max_length=50,null=True,blank=True)
    email = models.EmailField()
    number = models.PositiveIntegerField(null=True,blank=True)
    message = models.TextField()
    status = models.CharField(max_length=2,choices=ContactUs_choice,default="N")
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.profile:
            return self.profile.user.username
        return "Anonymous User"

support/forms.py
from django import forms
from support.models import ContactUs

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"
    

support/views.py
from json import loads
from django.http import JsonResponse
from django.shortcuts import render
from Product.views import popular
from django.urls import reverse
from .models import support_menu , Team
from django.template import Template , Context
from root.models import basic_setting
# Create your views here.
from django.views.decorators.cache import cache_page
from django.conf import settings


def mainView(request,slug):


    if request.GET.get('matRout'):
        if request.GET.get('popstate'):
            popstate = True
        else:
            popstate=False

        all_menu = support_menu.objects.all()
        return render(request,'chaldal/support/qs_as.html',{'menus':all_menu,'crnt_menu':slug,"popstate":popstate,"MEDIA_URL":settings.MEDIA_URL})

    routing_url = reverse("support:mainView",kwargs={"slug":slug})+"?matRout=True"
    return popular(request,routhing={"mat_router":routing_url})







def api(request):
    if request.GET.get('menu'):
        try:
            menu = support_menu.objects.get(slug=request.GET.get('menu'))
        except support_menu.DoesNotExist:
            return JsonResponse({"status":"faild",'data':'404 error'},status=404)

        context={
            'status':'successful',
            'menu_name':menu.name,
            'data':menu.body,
            'img':menu.img.url,
            'section':None
        }
        if request.GET.get('menu') == 'team':
            with open('/home/shihab2004/Chaldal/templates/chaldal/support/team_members.html','r') as f:
                team_html = f.read()
                all_team_members = []
                for members in Team.objects.all():
                    all_team_members.append({
                        'photo':members.photo.url,
                        'name':members.name,
                        'occupation':members.occupation,
                        'discription':members.discription,
                    })
                context.update({
                    'team_html':team_html,
                    'team_members_data':all_team_members,
                    'section':'team'
                })
        elif request.GET.get('menu') == 'contact-us':

            with open('/home/shihab2004/Chaldal/templates/chaldal/support/contuct-us-form.html','r') as f:
                templates = Template(f.read())
                context2 = Context({
                    "is_auth":request.user.is_authenticated,
                    'name':request.user if request.user.is_authenticated else "",
                    'email':request.user.email if request.user.is_authenticated else "",
                    'phone2':request.user.get_profile.Phone if request.user.is_authenticated else "",
                    "phone":basic_setting.objects.get().Mobile.all()[0].Phone
                })
                full_form_html = templates.render(context2)
                context.update({
                    'section':'contact-us',
                    'form_html':full_form_html
                })

        return JsonResponse(context)


from .forms import ContactUsForm
from re import match
def helpPost(request):
    user_profile = request.user.get_profile if request.user.is_authenticated else None
    data = loads(request.POST['data'])
    is_match = match('^(\+880|0)1(9|8|7|6|5|3)\d+',data['number'])
    if is_match:
        if len(is_match.string) < 14 or len(is_match.string) < 13 or len(is_match.string) < 10 or len(is_match.string) < 11:
            print('########################################')

            cous_form = ContactUsForm({
            'profile':user_profile,
            "name":data['name'],
            "email":data['email'],
            "number":is_match.string,
            "message":data['message'],
            "status":"N"
            })
            print(cous_form.errors)
            if cous_form.is_valid():
                cous_form.save()
                return JsonResponse({"status":"successful",'data':"Thanks for dropping us a note. We'll get back to you within 24 hours. For urgent matters, please call our hotline: 0188-1234567"})
        return JsonResponse({"status":"faild",'data':"Invalid Forms"})

    return JsonResponse({"status":"error",'data':"Invalid Number"})

templates/chaldal/support/contuct-us-form.html
<form id="contuctUsForm">
    <div class="inputContainer">
        <input class="has-value" name="name" type="text" value="{{name}}" /><span
            class="input-placeholder">Name</span><span class="input-error"></span><span
            class="input-description"></span><span class="input-extra-content"></span>
    </div>
    <div class="inputContainer">
        <input class="" name="email" type="email" required="" value="{{email}}" /><span style="top: -32px;font-weight: 300;font-size: 13px!important;" class="input-placeholder">Email
            Address</span><span class="input-error"></span><span class="input-description"></span><span
            class="input-extra-content"></span>
    </div>
    <div class="inputContainer">
        <input class="has-value" name="number" type="text" value="{% if is_auth %}0{% endif %}{% if phone2 %}{{phone2}}{% endif %}" /><span
            class="input-placeholder">Phone Number</span><span class="input-error"></span><span
            class="input-description"></span><span class="input-extra-content"></span>
    </div>
    <div class="inputContainer">
        <textarea class="" name="message" type="text" required="" rows="3"></textarea><span
            class="input-placeholder" style="top: -32px;font-weight: 300;font-size: 13px!important;">Message</span><span class="input-error"></span><span
            class="input-description"></span><span class="input-extra-content"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <div class="callUs">
        <span>Or call us</span><span>: </span><span>0{{phone}}</span>
    </div>
</form>

<script>
    $('#contuctUsForm button[type="submit"]').click((e)=>{
        const form = $('#contuctUsForm')
        e.preventDefault()
        $.ajax({
            type:'POST',
            url:"{% url 'support:contuctUs' %}",
            data:{
                "csrfmiddlewaretoken": csrfmiddlewaretoken,
                "data":JSON.stringify({
                    'name':form.find('input[name="name"]').val(),
                    'email':form.find('input[name="email"]').val(),
                    'number':form.find('input[name="number"]').val(),
                    'message':form.find('textarea[name="message"]').val()
                })
            },
            success:(data)=>alert(data.data)
        })
    })
</script>

templates/chaldal/support/qs_as.html
<section class="bodyTable">
    <div>
        <div class="topicPage">
            <div class="loaded">
                <div class="page-bg-image">
                    <div class="page-image" style="
             
              background-size: cover;
              background-position: center center;
              background-repeat: no-repeat;
             "></div>
                    <div class="page-title">FAQ</div>
                    <div class="link-section">
                        <ul class="page-link">
                            {% for menu in menus %}
                            <li class="links selectedLink">
                                <a class="itemLinks" href="{{menu.url}}">{{menu.name}}</a><span class=""></span>
                            </li>
                            {% endfor %}
                            

                        </ul>
                    </div>
                </div>
                <div>
                    <div class="body needHelpItemBody">
                       
                        
                      
           
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    var help__click = true;
     {% if  popstate %}
        var help__click = false;
    {% endif %}
    $('.itemLinks').click((e)=>{
        e.preventDefault()
        $('.itemLinks').parent().find('span').removeClass('itemUnderline')
        e.currentTarget.parentNode.children[1].classList.add('itemUnderline');
        $.ajax({
            type:'GET',
            url:e.currentTarget.href,
            success:(data)=>{
                setTitle(e.currentTarget.textContent)
                $('.page-title').text(data.menu_name)
                $('.body.needHelpItemBody').html(data.data)
                $('.page-image').css('background-image',`url(${data.img})`)
                const url = e.currentTarget.href.split('?')[1].split('=')[1]

                if(help__click){
                    url_routing(`/t/${url}/`)
                }
                not_click = true;
                if(data.section == 'team'){
                    $('.body.needHelpItemBody').append(`
                    <div class='team-page'>
                        <sction class='team-section'>
                        <div class="team-block"><div>
                        </sction>
                    </div>
                        `)
                    data.team_members_data.forEach((mem)=>{
                        const team_html = data.team_html
                        const html = team_html.replace('[[member_img]]',mem.photo).replace('[[member_name]]',mem.name).replace('[[occupation]]',mem.occupation).replace('[[discription]]',mem.discription).replace('[[media]]',"{{MEDIA_URL}}")
                        $('.team-block').append(html)
                    })

                    let old;
                    $('.individualTeam').click((e)=>{
                        if (old != e.currentTarget){
                        $('.individualTeam').removeClass('selected');
                        $('.individualTeam .arrowHolder').removeClass('nai');
                        }
                        e.currentTarget.classList.toggle('selected');
                        e.currentTarget.querySelector('.arrowHolder').classList.toggle('nai');
                        
                        old = e.currentTarget
                    })
                }else if(data.section == 'contact-us'){
                    $('.body.needHelpItemBody').append(data.form_html)
                }
            }
        })
    })
    {% if crnt_menu %}
   
    $('.itemLinks[href="/t/api/?menu={{crnt_menu}}"]')[0].click()
    console.log('{{crnt_menu}}')
    {% endif %}
</script>

templates/chaldal/support/team_members.html
<div class="individualTeam">
  <div class="img">
    <img src="[[member_img]]" size="210" style="background-color: transparent"/>
  </div>
  <div class="info-block">
    <div class="name">[[member_name]]</div>
    <div class="position">[[occupation]]</div>
    <div class="description">
      <span>[[discription]]</span>
    </div>
  </div>
  <div class="arrowClass">
    <div class="arrowHolder">
      <img
        src="[[media]]down-arrow.webp"
      />
    </div>
  </div>
</div>